name: Make DockerHub image
on:
  push:
    branches:
      - 'main'
jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get docker image version
        run: echo "DOCKER_IMAGE_VERSION=$(./get-version.sh)" >> $GITHUB_ENV
      - name: Print docker image version
        run: echo $DOCKER_IMAGE_VERSION
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "deemson/graphql-code-generator:$DOCKER_IMAGE_VERSION"
